[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "megpipeline"
authors = [{name = "Hadi Zaatiti", email = "hz3752@nyu.edu"}]
dynamic = ["version", "description"]
