name: Webhook Triggered Workflow

on:
  repository_dispatch:
    types: [box-event]

jobs:
  webhook_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "Triggered by Box Dev webhook"
