name: Docker test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t simple-tester .

    - name: Run Script in Docker Container
      run: |
        docker run --rm simple-tester
