name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi, thank you for submitting this issue, we will be discussing it and adressing it asap!"
        pr-message: "Thank you for your contribution we will shortly be reviewing your pull request."
