name: Trigger ReadTheDocs Build

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression triggers the action daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering via GitHub Actions UI

jobs:
  trigger-readthedocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Daily Trigger ReadTheDocs Build
        run: |
          curl -X POST "https://readthedocs.org/api/v3/projects/meg-pipeline/versions/latest/builds/" \
          -H "Authorization: Token ${{ secrets.READTHEDOCS_API_TOKEN }}"
