name: MEG Manual Generation

on:
  push:
    branches:
      - main  # You can change this to any branch you want
  pull_request:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Install Sphinx and dependencies
      - name: Install Sphinx and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt  # Make sure you have your Sphinx dependencies here

      # Step 4: Install LaTeX to build the PDF
      - name: Install LaTeX
        run: sudo apt-get install texlive-full -y

      # Step 5: Build the LaTeX output
      - name: Build LaTeX files from Sphinx
        run: |
          make -C docs latexpdf  # Change 'docs' if your conf.py is located in a different directory

      # Step 6: Upload PDF as an artifact
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdf
          path: docs/_build/latex/*.pdf  # Adjust the path based on where your build outputs the PDF
