name: Report Generation MEG Lab Manual

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-22.04

    env:
      BOX_CLIENT_ID: ${{ secrets.BOX_CLIENT_ID }}
      BOX_CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}
      BOX_ENTERPRISE_ID: ${{ secrets.BOX_ENTERPRISE_ID }}
      BOX_PUBLIC_KEY_ID: ${{ secrets.BOX_PUBLIC_KEY_ID }}
      BOX_PRIVATE_KEY: ${{ secrets.BOX_PRIVATE_KEY }}
      BOX_PASSPHRASE: ${{ secrets.BOX_PASSPHRASE }}
      PDF_GENERATION_INDEX: "LABMANUAL"

    steps:
      - name: Check out the code
        uses: actions/checkout@v3



      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade --no-cache-dir pip setuptools
          python -m pip install --upgrade --no-cache-dir sphinx
          python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
          python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir .

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build HTML documentation
        working-directory: docs/source
        run: |
          python -m sphinx -T --keep-going -b html -d ../../rtd-build-output/_build/doctrees -D language=en -D exclude_patterns="index.rst" . ../../rtd-build-output/html

      - name: Build LaTeX documentation
        working-directory: docs/source
        run: |
          python -m sphinx -T -b latex -d ../../rtd-build-output/_build/doctrees -D language=en . ../../rtd-build-output/pdf

      - name: Install TeX Live for LaTeX PDF generation
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xetex latexmk

      - name: Build PDF from LaTeX
        working-directory: rtd-build-output/pdf
        run: |
          latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=meg-pipeline -interaction=nonstopmode || true

      - name: Commit and Push PDF to Documents Directory
        if: ${{ success() }}
        run: |
          git config --global user.email "hadizaatiti@gmail.com"
          git config --global user.name "hzaatiti"
          mkdir -p documents
          cp rtd-build-output/pdf/meg-pipeline.pdf documents/meg-lab-manual.pdf
          git checkout main  # Ensure you are on the main branch
          git add documents/meg-pipeline.pdf
          git commit -m "Update PDF documentation" || echo "No changes to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Hzaatiti/meg-pipeline.git" main