name: RTD Replicate Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade --no-cache-dir pip setuptools
          python -m pip install --upgrade --no-cache-dir sphinx
          python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
          python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir .

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build HTML documentation
        working-directory: docs/source
        run: |
          python -m sphinx -T -W --keep-going -b html -d ../../rtd-build-output/_build/doctrees -D language=en . ../../rtd-build-output/html

      - name: Build LaTeX documentation
        working-directory: docs/source
        run: |
          python -m sphinx -T -b latex -d ../../rtd-build-output/_build/doctrees -D language=en . ../../rtd-build-output/pdf

      - name: Install TeX Live for LaTeX PDF generation
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xetex latexmk

      - name: Build PDF from LaTeX
        working-directory: rtd-build-output/pdf
        run: |
          latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=meg-pipeline -interaction=nonstopmode
