name: RTD Replicated Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install sphinx sphinx-rtd-theme  # Add any other required packages

      - name: Install LaTeX for PDF generation
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended latexmk

      - name: Build HTML documentation
        run: |
          sphinx-build -b html docs/source docs/_build/html

      - name: Build PDF documentation
        run: |
          sphinx-build -b latex docs/ docs/_build/latex
          cd docs/_build/latex
          latexmk -pdf -quiet -interaction=nonstopmode -f *.tex

      - name: Upload HTML documentation as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html

      - name: Upload PDF documentation as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf-docs
          path: docs/_build/latex/*.pdf
